return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 4,
  nextobjectid = 33,
  properties = {},
  tilesets = {
    {
      name = "Upscale-Grass",
      firstgid = 1,
      class = "",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      columns = 7,
      image = "../../../../../Downloads/Upscale-Grass.png",
      imagewidth = 448,
      imageheight = 192,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0,
      },
      grid = {
        orientation = "orthogonal",
        width = 64,
        height = 64,
      },
      properties = {},
      wangsets = {},
      tilecount = 21,
      tiles = {},
    },
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "dirt",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
        7,
      },
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 2,
      name = "grass",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        4,
        19,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        11,
        18,
        18,
        19,
        18,
        19,
        19,
        4,
        11,
        20,
        18,
        18,
        11,
        4,
        4,
        19,
        19,
        4,
        19,
        4,
        4,
        4,
        4,
        4,
        4,
        19,
        18,
        20,
        19,
        4,
        4,
        4,
        4,
        20,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        3,
        4,
        4,
        4,
        4,
        20,
        11,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        10,
        11,
        4,
        19,
        4,
        4,
        4,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        10,
        4,
        20,
        4,
        19,
        19,
        4,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        10,
        19,
        20,
        4,
        4,
        4,
        4,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        10,
        11,
        4,
        11,
        11,
        19,
        19,
        15,
        16,
        16,
        16,
        16,
        16,
        16,
        16,
        16,
        17,
        4,
        4,
        4,
        4,
        20,
        11,
        4,
        4,
        19,
        4,
        4,
        19,
        4,
        4,
        4,
        19,
        4,
        20,
        4,
        4,
        11,
        19,
        4,
        19,
        11,
        4,
        20,
        18,
        11,
        19,
        4,
        4,
        19,
        11,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        4,
        19,
        4,
        4,
        4,
        4,
        19,
        4,
        4,
      },
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "grow",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {},
        },
      },
    },
  },
}
